import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, BatteryCharging, Bell, ChevronDown, CircleHelp, CloudSun, Gauge, LayoutDashboard, MapPin, Menu, Settings, ShieldCheck, Sparkles, Sun, Wind, X, Zap } from 'lucide-react'
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import './App.css'

const navItems = [['Overview', LayoutDashboard, '/dashboard'], ['Communities', MapPin, '/communities'], ['Energy monitor', Activity, '/energy'], ['Weather intelligence', CloudSun, '/weather'], ['Optimizer', Sparkles, '/optimizer'], ['Forecast models', Gauge, '/forecast-models'], ['Alerts', Bell, '/alerts'], ['Reports', ShieldCheck, '/reports']]
const chartPoints = [28, 35, 31, 43, 51, 48, 62, 68, 60, 74, 80, 76, 88, 83, 91, 85, 79, 70, 63, 57, 49, 44, 38, 32]
const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000/api'

function DashboardPage({ data, token }) {
  const [selectedId, setSelectedId] = useState(1)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [optimizer, setOptimizer] = useState(null)
  const navigate = useNavigate()
  const communities = data?.communities || []
  const selected = communities.find((community) => community.id === selectedId) || communities[0]
  const runOptimizer = () => { if (!selected) return; fetch(`${API}/optimizer/run/`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ demand: selected.demand, solar_available: selected.solar, wind_available: selected.wind, battery_percent: selected.battery }) }).then((response) => response.json()).then(setOptimizer) }
  return <div className="app-shell">
    <aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark"><Zap size={18} fill="currentColor" /></div><div><strong>VECTOR</strong><small>ENERGY INTELLIGENCE</small></div><button className="icon-button close-menu" onClick={() => setMobileOpen(false)}><X size={18} /></button></div><div className="workspace-label">WORKSPACE <span>PRO</span></div><nav>{navItems.map(([label, Icon, path]) => <NavLink to={path} key={label} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'} onClick={() => setMobileOpen(false)}><Icon size={18} /><span>{label}</span>{label === 'Alerts' && <b className="nav-count">3</b>}</NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/settings" className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Settings size={18} /><span>Settings</span></NavLink><div className="user-card"><div className="avatar">AK</div><div><strong>Arjun Kapoor</strong><small>Company admin</small></div><ChevronDown size={15} /></div></div></aside>
    <main className="main-content"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><div><p className="eyebrow">OPERATIONS CENTER / <span>LIVE VIEW</span></p><h1>Good morning, Arjun <span className="wave">✦</span></h1></div><div className="top-actions"><div className="demo-pill"><span></span> Demo / Simulated data</div><button className="icon-button notification"><Bell size={19} /><i>3</i></button><div className="top-avatar">AK</div></div></header>
      {!data ? <div className="loading-state">Loading your microgrids...</div> : <><section className="context-row"><div><p className="section-kicker">NETWORK OVERVIEW</p><h2>All communities</h2></div><div className="selector"><MapPin size={16} /><select value={selectedId} onChange={(event) => setSelectedId(Number(event.target.value))}>{communities.map((community) => <option key={community.id} value={community.id}>{community.name} microgrid</option>)}</select><ChevronDown size={15} /></div><button className="primary-button" onClick={runOptimizer}><Sparkles size={16} /> Run optimizer</button></section>
      <section className="kpi-grid"><Kpi icon={MapPin} label="Active communities" value="05" meta="Across 3 states" tone="green" /><Kpi icon={Zap} label="Current demand" value={`${data.kpis.demand_mw} MW`} meta="Up 4.8% vs yesterday" tone="blue" /><Kpi icon={Sun} label="Renewable share" value={`${data.kpis.renewable_share}%`} meta="Up 6.2% this week" tone="lime" /><Kpi icon={BatteryCharging} label="Battery health" value={`${data.kpis.battery_health}%`} meta="All systems nominal" tone="amber" /><Kpi icon={Activity} label="Diesel offset" value={`${data.kpis.diesel_l} L`} meta="Down 18% this month" tone="teal" /></section>
      <section className="dashboard-grid"><div className="panel map-panel"><PanelHeading title="Community pulse" action="View map" /><div className="map-visual"><div className="map-grid"></div>{communities.map((community, index) => <button className={`map-marker ${community.status.toLowerCase()}`} key={community.id} style={{ left: `${18 + (index * 17)}%`, top: `${58 - (index % 3) * 18}%` }} onClick={() => navigate(`/communities/${community.id}`)}><span></span><b>{community.name}</b></button>)}<div className="map-label"><MapPin size={14} /> Rajasthan + Gujarat network</div></div><div className="map-footer"><span><i className="dot normal"></i> Normal <b>3</b></span><span><i className="dot warning"></i> Needs attention <b>1</b></span><span><i className="dot critical"></i> Critical <b>1</b></span></div></div>
      <div className="panel weather-panel"><PanelHeading title="Weather intelligence" action="Open forecast" /><div className="weather-main"><div><p className="muted">{selected?.name || 'Rampur'} / NOW</p><strong>{data.weather.temperature}°</strong><span>Clear skies</span></div><Sun className="sun-icon" size={68} strokeWidth={1.2} /></div><div className="weather-stats"><WeatherStat icon={Wind} label="Wind speed" value={`${data.weather.wind} km/h`} /><WeatherStat icon={CloudSun} label="Solar radiation" value={`${data.weather.solar} W/m2`} /><WeatherStat icon={CloudSun} label="Rain probability" value={`${data.weather.rain}%`} /></div><div className="forecast-note"><Sparkles size={16} /><span><b>Forecast signal</b> Solar generation may dip 35% between 2 PM and 5 PM.</span></div></div>
      <div className="panel chart-panel"><PanelHeading title="Energy performance" action="24 hours" /><div className="chart-summary"><div><p className="muted">Renewable generation</p><strong>468 <small>kW avg</small></strong></div><div className="legend"><span><i className="solar"></i>Solar</span><span><i className="wind"></i>Wind</span><span><i className="demand"></i>Demand</span></div></div><div className="line-chart"><svg viewBox="0 0 800 210" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9bdcc3" stopOpacity=".48" /><stop offset="100%" stopColor="#9bdcc3" stopOpacity="0" /></linearGradient></defs><path d={`M 0 190 ${chartPoints.map((point, index) => `L ${(index / 23) * 800} ${190 - point * 1.65}`).join(' ')} L 800 210 L 0 210 Z`} fill="url(#chartFill)" /><path d={`M 0 190 ${chartPoints.map((point, index) => `L ${(index / 23) * 800} ${190 - point * 1.65}`).join(' ')}`} fill="none" stroke="#319f78" strokeWidth="3" /></svg><div className="x-axis"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>Now</span></div></div></div>
      <div className="panel recommendation-panel"><div className="recommendation-top"><div><p className="section-kicker">VECTOR SMART RECOMMENDATION</p><h3>{selected?.name || 'Rampur'} microgrid</h3></div><span className="confidence"><Sparkles size={14} /> 91% confidence</span></div><p className="recommendation-copy">Weather-aware dispatch for the next operating window. Keep diesel in reserve while the battery absorbs the forecast dip.</p><div className="energy-mix">{[['solar', 'Solar', optimizer?.solar_kw ?? 60, Sun], ['wind', 'Wind', optimizer?.wind_kw ?? 25, Wind], ['battery', 'Battery', optimizer?.battery_kw ?? 15, BatteryCharging], ['diesel', 'Diesel', optimizer?.diesel_kw ?? 0, Zap]].map(([type, label, value, Icon]) => <div className="mix-row" key={label}><span className={`mix-icon ${type}`}><Icon size={16} /></span><b>{label}</b><div className="mix-track"><i className={type} style={{ width: `${Math.min((value / 100) * 100, 100)}%` }}></i></div><strong>{value} <small>kW</small></strong></div>)}</div><div className="recommendation-footer"><span><ShieldCheck size={15} /> Demand fully met</span><span><ShieldCheck size={15} /> Diesel avoided</span>{optimizer && <span className="calculated">Cost Rs {optimizer.cost_per_hour}/hr · {optimizer.co2_kg_per_hour} kg CO2</span>}</div></div></section>
      <section className="lower-grid"><div className="panel communities-panel"><PanelHeading title="Community status" action="See all 5" /><div className="table-wrap"><table><thead><tr><th>Community</th><th>Demand</th><th>Renewable</th><th>Battery</th><th>Status</th></tr></thead><tbody>{communities.map((community) => <tr key={community.id} onClick={() => navigate(`/communities/${community.id}`)}><td><span className="table-pin"><MapPin size={14} /></span><div><b>{community.name}</b><small>{community.district}, {community.state}</small></div></td><td>{community.demand} kW</td><td><strong className="renewable-value">{community.renewable}%</strong></td><td><div className="battery-cell"><div><i style={{ width: `${community.battery}%` }}></i></div>{community.battery}%</div></td><td><span className={`status ${community.status.toLowerCase()}`}><i></i>{community.status}</span></td></tr>)}</tbody></table></div></div><div className="panel alerts-panel"><PanelHeading title="Latest alerts" action="View all" /><Alert severity="critical" title="Battery reserve low" text="Bharatpur is below the 20% safe threshold." time="8 min ago" /><Alert severity="warning" title="Solar forecast dip" text="Expected decrease of 35% this afternoon." time="42 min ago" /><Alert severity="info" title="Charge recommendation" text="Rampur battery charging window is open." time="1 hr ago" /></div></section></>}
      <footer>VECTOR / Renewable Energy Intelligence Platform <span>Last synced 2 min ago · <b>All systems operational</b></span></footer></main>
  </div>
}
function Kpi({ icon: Icon, label, value, meta, tone }) { return <div className="kpi-card"><div className={`kpi-icon ${tone}`}><Icon size={18} /></div><p>{label}</p><strong>{value}</strong><small>{meta}</small></div> }
function PanelHeading({ title, action }) { return <div className="panel-heading"><h3>{title}</h3><button>{action} <span>↗</span></button></div> }
function WeatherStat({ icon: Icon, label, value }) { return <div><Icon size={15} /><span>{label}</span><b>{value}</b></div> }
function Alert({ severity, title, text, time }) { return <div className="alert"><div className={`alert-icon ${severity}`}>{severity === 'critical' ? <AlertTriangle size={15} /> : severity === 'warning' ? <CloudSun size={15} /> : <CircleHelp size={15} />}</div><div><b>{title}</b><p>{text}</p><small>{time}</small></div></div> }
function Login({ onLogin }) {
  const [email, setEmail] = useState('admin@vector.local')
  const [password, setPassword] = useState('VectorDemo!2026')
  const [error, setError] = useState('')
  const submit = (event) => { event.preventDefault(); fetch(`${API}/auth/login/`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }).then((response) => response.json().then((body) => ({ ok: response.ok, body }))).then(({ ok, body }) => ok ? onLogin(body.access) : setError(body.detail || 'Unable to sign in.')) .catch(() => setError('API unavailable.')) }
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><div className="brand-mark"><Zap size={18} fill="currentColor" /></div><p className="section-kicker">VECTOR / OPERATIONS CENTER</p><h1>Sign in</h1><p className="muted">Access weather intelligence and energy dispatch.</p><label>Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" /></label><label>Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" /></label>{error && <p className="login-error">{error}</p>}<button className="primary-button" type="submit">Sign in <ShieldCheck size={16} /></button></form></main>
}

function PageShell({ children, title, kicker = 'VECTOR / OPERATIONS CENTER', data }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  return <div className="app-shell"><aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark"><Zap size={18} fill="currentColor" /></div><div><strong>VECTOR</strong><small>ENERGY INTELLIGENCE</small></div><button className="icon-button close-menu" onClick={() => setMobileOpen(false)}><X size={18} /></button></div><div className="workspace-label">WORKSPACE <span>PRO</span></div><nav>{navItems.map(([label, Icon, path]) => <NavLink to={path} key={label} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'} onClick={() => setMobileOpen(false)}><Icon size={18} /><span>{label}</span>{label === 'Alerts' && <b className="nav-count">{data?.alerts || 0}</b>}</NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/settings" className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Settings size={18} /><span>Settings</span></NavLink><div className="user-card"><div className="avatar">AK</div><div><strong>Arjun Kapoor</strong><small>Company admin</small></div><ChevronDown size={15} /></div></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><div><p className="eyebrow">{kicker} / <span>LIVE VIEW</span></p><h1>{title}</h1></div><div className="top-actions"><div className="demo-pill"><span></span> Demo / Simulated data</div><NavLink className="icon-button notification" to="/alerts"><Bell size={19} /><i>{data?.alerts || 0}</i></NavLink><div className="top-avatar">AK</div></div></header>{children}<footer>VECTOR / Renewable Energy Intelligence Platform <span>Authenticated workspace · <b>All systems operational</b></span></footer></main></div>
}

function DataPanel({ title, children, action }) { return <section className="panel route-panel"><PanelHeading title={title} action={action} />{children}</section> }
function MetricGrid({ items }) { return <div className="kpi-grid route-kpis">{items.map(([label, value, meta], index) => <Kpi key={label} icon={[Zap, Sun, Wind, BatteryCharging, Activity][index % 5]} label={label} value={value} meta={meta} tone={['green', 'lime', 'blue', 'amber', 'teal'][index % 5]} />)}</div> }
function CommunitiesPage({ data }) { return <PageShell title="Communities" data={data}><section className="context-row"><div><p className="section-kicker">NETWORK DIRECTORY</p><h2>Rural microgrids</h2></div><span className="demo-pill">{data?.communities?.length || 0} connected sites</span></section><div className="community-grid">{(data?.communities || []).map((community) => <NavLink className="panel community-card" to={`/communities/${community.id}`} key={community.id}><div className="community-card-top"><span className={`status ${community.status.toLowerCase()}`}><i></i>{community.status}</span><MapPin size={17} /></div><h3>{community.name}</h3><p>{community.district}, {community.state}</p><div className="community-card-stats"><span><b>{community.demand} kW</b>Demand</span><span><b>{community.renewable}%</b>Renewable</span><span><b>{community.battery}%</b>Battery</span></div><span className="text-link">Open community <span>↗</span></span></NavLink>)}</div></PageShell> }
function CommunityPage({ data, token }) { const { id } = useParams(); const community = data?.communities?.find((item) => String(item.id) === id); if (!community) return <PageShell title="Community not found" data={data}><EmptyState text="This community is not available to your role." /></PageShell>; return <PageShell title={`${community.name} microgrid`} kicker="COMMUNITY DETAIL" data={data}><section className="context-row"><div><p className="section-kicker">{community.district}, {community.state}</p><h2>Operational snapshot</h2></div><NavLink className="primary-button" to="/optimizer"><Sparkles size={16} /> Open optimizer</NavLink></section><MetricGrid items={[["Current demand", `${community.demand} kW`, "Live operating load"], ["Solar generation", `${community.solar} kW`, "Current availability"], ["Wind generation", `${community.wind} kW`, "Current availability"], ["Battery reserve", `${community.battery}%`, "State of charge"], ["Renewable share", `${community.renewable}%`, "Current mix"]]} /><div className="route-columns"><DataPanel title="Weather signal" action="Open weather"><div className="detail-list"><span>Temperature <b>Unavailable</b></span><span>Solar radiation <b>Stored forecast</b></span><span>Wind conditions <b>{community.wind} kW available</b></span><span>Cloud cover <b>Open forecast for live data</b></span></div></DataPanel><DataPanel title="Energy forecast" action="Forecast models"><div className="empty-inline"><Gauge size={20} /><span>Run a model forecast to project solar and wind generation for this site.</span></div></DataPanel></div></PageShell> }
function WeatherPage({ data, token }) { const [forecast, setForecast] = useState(null); const selected = data?.communities?.[0]; useEffect(() => { if (!selected || !token) return; fetch(`${API}/weather/${selected.id}/forecast/`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.ok ? response.json() : null).then(setForecast) }, [selected, token]); return <PageShell title="Weather intelligence" data={data}><section className="context-row"><div><p className="section-kicker">OPEN-METEO SIGNALS</p><h2>{selected?.name || 'Selected community'}</h2></div><span className="demo-pill">{forecast?.source || 'Forecast unavailable'}</span></section><MetricGrid items={[["Current conditions", forecast?.forecast?.[0]?.temperature ? `${forecast.forecast[0].temperature}°C` : 'Unavailable', "Latest stored reading"], ["Solar radiation", forecast?.forecast?.[0]?.solar_radiation ? `${forecast.forecast[0].solar_radiation} W/m²` : 'Unavailable', "Forecast signal"], ["Wind speed", forecast?.forecast?.[0]?.wind_speed ? `${forecast.forecast[0].wind_speed} km/h` : 'Unavailable', "Forecast signal"], ["Cloud cover", forecast?.forecast?.[0]?.cloud_cover ? `${forecast.forecast[0].cloud_cover}%` : 'Unavailable', "Forecast signal"], ["Precipitation", forecast?.forecast?.[0]?.precipitation ? `${forecast.forecast[0].precipitation} mm` : 'Unavailable', "Forecast signal"]]} /><DataPanel title="24-hour and 7-day forecast"><div className="forecast-table">{(forecast?.forecast || []).slice(0, 12).map((row) => <div key={row.timestamp}><b>{new Date(row.timestamp).toLocaleString([], { weekday: 'short', hour: '2-digit' })}</b><span>{row.temperature ?? '--'}°C</span><span>{row.solar_radiation ?? '--'} W/m²</span><span>{row.wind_speed ?? '--'} km/h</span><span>{row.cloud_cover ?? '--'}% cloud</span></div>)}{!forecast?.forecast?.length && <EmptyState text="Forecast unavailable. Open-Meteo data will appear here when available." />}</div></DataPanel></PageShell> }
function OptimizerPage({ data, token }) { const [result, setResult] = useState(null); const community = data?.communities?.[0]; const run = () => community && fetch(`${API}/optimizer/run/`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ demand: community.demand, solar_available: community.solar, wind_available: community.wind, battery_percent: community.battery }) }).then((response) => response.json()).then(setResult); return <PageShell title="Energy optimizer" data={data}><section className="context-row"><div><p className="section-kicker">FORECAST-AWARE DISPATCH</p><h2>{community?.name || 'Community'}</h2></div><button className="primary-button" onClick={run}><Sparkles size={16} /> Run optimization</button></section><MetricGrid items={[["Current demand", `${community?.demand || '--'} kW`, "Operating load"], ["Solar available", `${community?.solar || '--'} kW`, "Current source"], ["Wind available", `${community?.wind || '--'} kW`, "Current source"], ["Battery state", `${community?.battery || '--'}%`, "Reserve protected"], ["Diesel price", "Rs 92", "Configured input"]]} /><DataPanel title="Recommended energy mix"><div className="optimizer-result">{result ? [['Solar', result.solar_kw], ['Wind', result.wind_kw], ['Battery', result.battery_kw], ['Diesel', result.diesel_kw]].map(([label, value]) => <div className="optimizer-line" key={label}><b>{label}</b><span className="mix-track"><i className={label.toLowerCase()} style={{ width: `${Math.min((value / (community?.demand || 1)) * 100, 100)}%` }} /></span><strong>{value} kW</strong></div>) : <EmptyState text="Run optimization to calculate a weather-aware dispatch recommendation." />}</div>{result && <div className="recommendation-footer"><span>Renewable share {result.renewable_share}%</span><span>Cost Rs {result.cost_per_hour}/hr</span><span>CO₂ {result.co2_kg_per_hour} kg/hr</span></div>}</DataPanel></PageShell> }
function ForecastModelsPage({ data, token }) { const community = data?.communities?.[0]; const [models, setModels] = useState(null); const [training, setTraining] = useState(false); const load = () => community && fetch(`${API}/models/${community.id}/`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then(setModels); useEffect(() => { load() }, [community?.id, token]); const train = () => { setTraining(true); fetch(`${API}/models/${community.id}/train/`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => { setModels(body); setTraining(false) }).catch(() => setTraining(false)) }; return <PageShell title="Forecast models" data={data}><section className="context-row"><div><p className="section-kicker">MODEL PERFORMANCE</p><h2>{community?.name || 'Community'} comparison</h2></div><button className="primary-button" onClick={train} disabled={training}><Gauge size={16} /> {training ? 'Training...' : 'Train models'}</button></section><DataPanel title="XGBoost vs LSTM"><div className="model-table"><div className="model-row model-header"><b>Target</b><b>Model</b><b>MAE</b><b>RMSE</b><b>Status</b></div>{(models?.models || models?.results?.flatMap((item) => Object.entries(item.metrics).filter(([, metric]) => metric).map(([name, metric]) => ({ target_variable: item.target_variable, model_name: name, ...metric, selected: item.selected_model === name }))) || []).map((model, index) => <div className="model-row" key={`${model.target_variable}-${model.model_name}-${index}`}><span>{model.target_variable}</span><span>{model.model_name}</span><span>{model.mae}</span><span>{model.rmse}</span><strong>{model.selected ? 'Selected' : 'Compared'}</strong></div>)}{!models && <EmptyState text="No trained models yet. Start a training run to compare validation accuracy." />}</div></DataPanel></PageShell> }
function AlertsPage({ data, token }) { const [alerts, setAlerts] = useState([]); useEffect(() => { fetch(`${API}/alerts/`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then((body) => setAlerts(body.alerts || [])) }, [token]); return <PageShell title="Alerts" data={{ ...data, alerts: alerts.filter((alert) => !alert.read).length }}><section className="context-row"><div><p className="section-kicker">RESPONSE QUEUE</p><h2>Active signals</h2></div></section><DataPanel title={`${alerts.filter((alert) => !alert.read).length} unread alerts`}>{alerts.length ? alerts.map((alert) => <div className="alert route-alert" key={alert.id}><div className={`alert-icon ${alert.severity}`}><AlertTriangle size={15} /></div><div><b>{alert.title}</b><p>{alert.message}</p><small>{new Date(alert.created_at).toLocaleString()}</small></div></div>) : <EmptyState text="No stored alerts for the communities in your workspace." />}</DataPanel></PageShell> }
function GenericPage({ title, kicker, data, children }) { return <PageShell title={title} kicker={kicker} data={data}><section className="context-row"><div><p className="section-kicker">{kicker}</p><h2>{title}</h2></div></section>{children || <DataPanel title="Workspace view"><EmptyState text="This operational view is ready for live data integration." /></DataPanel>}</PageShell> }
function EmptyState({ text }) { return <div className="empty-state"><CircleHelp size={20} /><span>{text}</span></div> }

function App() {
  const [token, setToken] = useState(() => sessionStorage.getItem('vector_access'))
  const [data, setData] = useState(null)
  useEffect(() => { if (!token) return; fetch(`${API}/dashboard/`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.ok ? response.json() : Promise.reject(response)).then(setData).catch(() => { sessionStorage.removeItem('vector_access'); setToken(null) }) }, [token])
  const login = (access) => { sessionStorage.setItem('vector_access', access); setToken(access) }
  return <BrowserRouter><Routes>{!token ? <><Route path="/login" element={<Login onLogin={login} />} /><Route path="*" element={<Navigate to="/login" replace />} /></> : <><Route path="/login" element={<Navigate to="/dashboard" replace />} /><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="/dashboard" element={<DashboardPage data={data} token={token} />} /><Route path="/communities" element={<CommunitiesPage data={data} />} /><Route path="/communities/:id" element={<CommunityPage data={data} token={token} />} /><Route path="/weather" element={<WeatherPage data={data} token={token} />} /><Route path="/optimizer" element={<OptimizerPage data={data} token={token} />} /><Route path="/forecast-models" element={<ForecastModelsPage data={data} token={token} />} /><Route path="/alerts" element={<AlertsPage data={data} token={token} />} /><Route path="/energy" element={<GenericPage title="Energy monitor" kicker="LIVE GENERATION" data={data}><MetricGrid items={[["Network demand", `${data?.kpis?.demand_mw || '--'} MW`, "Current demand"], ["Renewable share", `${data?.kpis?.renewable_share || '--'}%`, "Network average"], ["Battery health", `${data?.kpis?.battery_health || '--'}%`, "Reserve status"]]} /></GenericPage>} /><Route path="/reports" element={<GenericPage title="Reports" kicker="OPERATING HISTORY" data={data} />} /><Route path="/users" element={<GenericPage title="Users" kicker="ACCESS CONTROL" data={data} />} /><Route path="/settings" element={<GenericPage title="Settings" kicker="WORKSPACE CONFIGURATION" data={data} />} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></>}</Routes></BrowserRouter>
}

export default App
