# Generated by Django 4.2.9 on 2026-09-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(default='NORMAL', max_length=20)),
                ('average_demand_kw', models.FloatField(default=100)),
                ('solar_capacity_kw', models.FloatField(default=100)),
                ('wind_capacity_kw', models.FloatField(default=50)),
                ('battery_capacity_kwh', models.FloatField(default=500)),
                ('diesel_capacity_kw', models.FloatField(default=100)),
                ('battery_minimum_percentage', models.FloatField(default=20)),
                ('diesel_fuel_price', models.FloatField(default=92)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('demand_kw', models.FloatField()),
                ('solar_kw', models.FloatField()),
                ('wind_kw', models.FloatField()),
                ('battery_kw', models.FloatField()),
                ('diesel_kw', models.FloatField()),
                ('cost', models.FloatField()),
                ('co2', models.FloatField()),
                ('recommendation', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.community')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('demand_kw', models.FloatField()),
                ('solar_kw', models.FloatField()),
                ('wind_kw', models.FloatField()),
                ('battery_kw', models.FloatField()),
                ('diesel_kw', models.FloatField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.community')),
            ],
        ),
    ]
